http {
    # Log format
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';

    server {
        listen 80;

        # Access log configuration
        access_log /var/log/nginx/access.log main;

        # Error log configuration
        error_log /var/log/nginx/error.log warn;

        location /common/ {
            proxy_pass $COMMON_URL;
            proxy_set_header Host $host;
        }
    }
}

events {}
